#!/bin/sh

# This helps to see what is going on
set -e -x

DESTDIR="$(mktemp -d /tmp/imagebuilder-qemu_aarch64.XXXXXX)"

# copy output artifacts to DESTDIR
cp -r /home/builder/output-dom0-builder-qemu_aarch64 ${DESTDIR}
cp -r /home/builder/output-viryaos-xen-boot-aarch64 ${DESTDIR}
cp -r /home/builder/output-viryaos-grub ${DESTDIR}

cp /home/builder/viryaos.dtb ${DESTDIR}

mkdir ${DESTDIR}/viryaos-xen 
cd ${DESTDIR}/viryaos-xen 

tar zxvf ${DESTDIR}/output-viryaos-xen-boot-aarch64/viryaos-xen-boot.tar.gz

cd ${DESTDIR}

_vmlinuz=$(basename ${DESTDIR}/output-dom0-builder-qemu_aarch64/vmlinuz-*)
_fullkver=${_vmlinuz#vmlinuz-}

# remove unnecessary symlinks and config file
find ${DESTDIR}/viryaos-xen/boot -type l -exec rm {} \;
rm ${DESTDIR}/viryaos-xen/boot/xen-*.config

_xen=$(basename ${DESTDIR}/viryaos-xen/boot/xen-*)
_fullxenver=${_xen#xen-}

# grub.cfg
cat <<-EOF > ${DESTDIR}/grub.cfg
set timeout=1
set gfxpayload=text

menuentry "Linux" {
    insmod part_gpt
    insmod ext2

    set root=(hd2,gpt2)

    xen_hypervisor /boot/xen-$_fullxenver placeholder dom0_mem=1G
    xen_module     /boot/vmlinuz-$_fullkver console="hvc0" modules=loop,squashfs rootfs_cpio
    xen_module     /boot/initramfs-$_fullkver
    devicetree     /boot/viryaos.dtb
}
EOF

OUTDIR="/tmp/img"
mkdir ${OUTDIR}

IMG="${OUTDIR}/qemu_aarch64.img"

# Both GPT partitions and VFAT filesystem uses 512 as the default
# sector size
_sector_size=512 
_esp_file="${DESTDIR}/esp.img"

# For now we assume 16384 KiB, which is 32768 sectors
_esp_file_size_kib=16384

mkfs.vfat -v -C $_esp_file $_esp_file_size_kib
mmd -i $_esp_file ::/EFI
mmd -i $_esp_file ::/EFI/BOOT

mcopy -i $_esp_file -s ${DESTDIR}/output-viryaos-grub/BOOTAA64.EFI ::/EFI/BOOT/
mcopy -i $_esp_file -s ${DESTDIR}/grub.cfg ::/grub.cfg

# NOTE: Increase vos_a to 256 to accomodate rootfs
# 528 MiB (256 + 256 + 16)
truncate $IMG -s 528M

# create GPT partition table
sgdisk -og $IMG

_esp_file_size_bytes=$(( $_esp_file_size_kib * 1024 ))
_esp_file_size_sectors=$(( $_esp_file_size_bytes / $_sector_size ))

# start ESP at sector 2048
_esp_sector_start=2048
_esp_sector_end=$(( $_esp_sector_start + $_esp_file_size_sectors - 1 ))

# create EFI System Partition
sgdisk -n 1:$_esp_sector_start:$_esp_sector_end -c 1:"EFI System Partition" -t 1:ef00 $IMG

# copy ESP file over to IMG
dd if=$_esp_file of=$IMG bs=$_sector_size count=$_esp_file_size_sectors conv=notrunc seek=$_esp_sector_start

# _sector_first is obtained by running
# ```
# sgdisk -F /tmp/img/qemu_aarch64.img
# ```
_sector_first=34816

# _sector_last is obtained by running
# ```
# sgdisk -n 2:34816:+256M -c 2:"Linux" -t 2:8300 /tmp/img/qemu_aarch64.img
# ```
_sector_last=1081310

# create linux partition
sgdisk -n 2:$_sector_first:$_sector_last -c 2:"Linux" -t 2:8300 $IMG

# find the first available loop device
_loop_dev=$(sudo losetup -f)

# attach loopback device to $IMG
losetup $_loop_dev $IMG

_disksize=$(sudo blockdev --getsize $_loop_dev)

dmsetup create diskimage --table "0 $_disksize linear $_loop_dev 0"

# ensure that /dev/mapper/diskimage exists
while [ ! -b /dev/mapper/diskimage ]
do                      
	sleep 2
done

kpartx -a /dev/mapper/diskimage

# ensure that /dev/mapper/{diskimage1,diskimage2,diskimage3} exists
while [ ! -b /dev/mapper/diskimage1 ] || [ ! -b /dev/mapper/diskimage2 ]
do
	sleep 2
done
								 
# format vos_a partition
# NOTE: vos_a and vos_b will have a dependency with initramfs-init script
mkfs.ext4 -L vos_a -F /dev/mapper/diskimage2

# create mount point and mount vos_a
mkdir -p ${DESTDIR}/part/vos_a
mount -t ext4 /dev/mapper/diskimage2 $DESTDIR/part/vos_a

# Extract rootfs cpio archive into `.../part/vos_a`
$(cd ${DESTDIR}/part/vos_a; cpio -idm < ${DESTDIR}/output-dom0-builder-qemu_aarch64/rootfs.cpio)

# copy over files needed in `/boot`
mkdir ${DESTDIR}/part/vos_a/boot
# linux
cp ${DESTDIR}/output-dom0-builder-qemu_aarch64/initramfs-${_fullkver} ${DESTDIR}/part/vos_a/boot
cp ${DESTDIR}/output-dom0-builder-qemu_aarch64/modloop-${_fullkver}   ${DESTDIR}/part/vos_a/boot
cp ${DESTDIR}/output-dom0-builder-qemu_aarch64/vmlinuz-${_fullkver}   ${DESTDIR}/part/vos_a/boot
# xen
cp ${DESTDIR}/viryaos-xen/boot/xen-${_fullxenver}                     ${DESTDIR}/part/vos_a/boot
# dtb
cp ${DESTDIR}/viryaos.dtb                                             ${DESTDIR}/part/vos_a/boot

# unmount
sync

# This fails for some reason.
# fstrim $DESTDIR/part/vos_a

umount $DESTDIR/part/vos_a
kpartx -d /dev/mapper/diskimage
dmsetup remove diskimage
losetup -d $_loop_dev

